<?php

namespace App\Controller\Admin;

use App\Entity\Campus;
use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class UserCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return User::class;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('username'),
            TextField::new('firstName'),
            TextField::new('lastName'),
            TextField::new('phoneNumber'),
            TextField::new('email'),
            BooleanField::new('active'),
            BooleanField::new('admin'),
            TextField::new('campus'),
        ];
    }

    public function configureActions(Actions $actions): Actions
    {
        return parent ::configureActions($actions); // TODO: Change the autogenerated stub
    }


}
